#!/bin/bash

set -e

APP_TARGET=${APP_TARGET:-/app}

mkdir -p ${APP_TARGET}/src

echo "---> Installing application source"
cp -Rf /tmp/sti/src ${APP_TARGET}/src

cd ${APP_TARGET}/src
echo "---> Building Spring Boot application from source"
echo "--> # MVN_ARGS = $MVN_ARGS"
if [ -f "mvnw" ]; then
  ./mvnw clean install $MVN_ARGS
else
  mvn clean install $MVN_ARGS
fi

# Fix source directory permissions
fix-permissions ./
