#!/bin/sh

cat <<EOF
This is a STI springboot maven3 alpine base image:
To use it, install STI: https://github.com/openshift/source-to-image

Sample invocation:

sti build git://github.com/codecentric/springboot-sample-app tkaefer/springboot-maven3-s2i-alpine springboot-sample-app


You can then run the resulting image via:
docker run -p 8080:8080 springboot-sample-app
EOF
